name: CI
on: [push, pull_request]

jobs:
  vader-tests:
    name: Vader tests
    strategy:
      matrix:
        os: [ubuntu-latest]
        neovim: [true, false]
        version: [nightly, stable]
        exclude:
          - neovim: false
            version: stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: vader.vim
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - uses: actions/setup-python@v1
      - name: Install nvr
        run: |
          pip install neovim-remote
          nvr --version
      - name: Config git # otherwise test_gitcommit will fail
        run: |
          git config --global user.email "dyzplus@gmail.com"
          git config --global user.name "voldikss"
      - name: Run vader tests
        env:
          VIM_EXEC: ${{ steps.vim.outputs.executable }}
        run: |
          $VIM_EXEC --version
          for f in `find test/*/*.vader`
          do
              $VIM_EXEC -u test/vimrc -c "Vader! $f"
          done

  vint:
    name: Run vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint --error --verbose --enable-neovim --color --style ./autoload ./plugin
